spring.application.name=kafka

## RedHat Kafka Connection
#spring.kafka.bootstrap-servers=${kafka.bootstrap.server}
#spring.kafka.properties.security.protocol=SSL
#spring.kafka.properties.ssl.truststore.location=${kafka.truststore.location}
#spring.kafka.properties.ssl.truststore.password=${kafka.truststore.password}
#spring.kafka.properties.ssl.keystore.location=${kafka.keystore.location}
#spring.kafka.properties.ssl.keystore.password=${kafka.keystore.password}
#spring.kafka.properties.ssl.truststore.type=PKCS12
#spring.kafka.properties.ssl.keystore.type=PKCS12

##Local Kafka Connection
#spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.consumer.group-id=dynamic-group
#spring.kafka.consumer.auto-offset-reset=earliest
#spring.kafka.consumer.enable-auto-commit=true

spring.datasource.url=${kafkadb.url}
spring.datasource.username=${kafkadb.username}
spring.datasource.password=${kafkadb.password}
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.root=INFO
logging.level.commit.demo.kafka=DEBUG
logging.file.name=logs/application.log
logging.file.max-size=10MB
logging.file.total-size-cap=50MB
logging.file.max-history=10
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
